version: '2'
services:
  angular:
    build: angular-client
    image: pablogm/angular-client
    container_name: angular_container
    volumes:
      - ./angular-client:/usr/src/app/
      - angular-client-modules:/usr/src/app/node_modules
    ports:
      - '4200:4200'
      - '49153:49153' #Port of Webpack for live reloading
    depends_on:
      - express

  express:
    build: express-server
    image: pablogm/express-server
    container_name: express_container
    volumes:
      - ./express-server:/usr/src/app/
      - server-modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      MONGODB_ADMIN_DATABASE: $MONGODB_ADMIN_DATABASE
      MONGODB_ADMIN_USER: $MONGODB_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGODB_ADMIN_PASS

  database:
    image: mongo:3.4.2
    container_name: mongo_container
    volumes:
      - 'db-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: $MONGODB_ADMIN_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ADMIN_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ADMIN_PASS

volumes:
  db-data:
  server-modules:
  angular-client-modules:

